[package]
name = "dubbo-rust-helloworld"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "hello-server"
path = "src/server/main.rs"

[[bin]]
name = "hello-client"
path = "src/client/main.rs"

[dependencies]
http = "0.2"
http-body = "0.4.4"
futures-util = {version = "0.3", default-features = false}
tokio = { version = "1.0", features = [ "rt-multi-thread", "time", "fs", "macros", "net", "signal"] }
prost-derive = {version = "0.10", optional = true}
prost = "0.10.4"
prost-types = { version = "0.8", default-features = false }
async-trait = "0.1.56"
tokio-stream = "0.1"

dubbo = {git = "https://github.com/yang20150702/dubbo-rust.git"}

[build-dependencies]
dubbo-build = {git = "https://github.com/yang20150702/dubbo-rust.git"}